version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.0
    - 3.9.1
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: vue-i18n
    versions:
    - 8.23.0
    - 8.24.0
    - 8.24.1
    - 8.24.2
    - 8.24.3
  - dependency-name: "@nuxtjs/device"
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: nuxt
    versions:
    - 2.15.0
    - 2.15.1
    - 2.15.2
    - 2.15.3
    - 2.15.4
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.35
  - dependency-name: "@fortawesome/fontawesome-free"
    versions:
    - 5.15.3
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.3
  - dependency-name: "@nuxtjs/axios"
    versions:
    - 5.13.0
    - 5.13.1
  - dependency-name: "@nuxtjs/pwa"
    versions:
    - 3.3.5
